### ISSUE TITLE
AttributeError: module 'sympy' has no attribute 'compatibility'

### ISSUE THREAD

**Issue by YourHelper1** [cbm755/octsympy#1048] opened 2021-06-06 18:50 UTC
I have installed sympy in my Ubuntu 18.04 laptop and both python,python3,pip,pip3,sympy and symbolics on octave succesfully. I have also installed symbolics from command line like:
`sudo apt-get install octave-symbolic` ,all succesfully but when i try `syms x` or `syms('x')`  i get all those errors:

```
Symbolic pkg v2.9.0: Traceback (most recent call last):
  File "<stdin>", line 28, in <module>
AttributeError: '_PrintFunction' object has no attribute '__globals__'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 12, in octoutput_drv
  File "<stdin>", line 54, in octoutput
  File "<stdin>", line 55, in octoutput
AttributeError: module 'sympy' has no attribute 'compatibility'

Closing the Python communications link.
error: Python exception: AttributeError: '_PrintFunction' object has no attribute '__globals__'
    occurred in python_header import block.
    Try "sympref reset" and repeat your command?
    (consider filing an issue at https://github.com/cbm755/octsympy/issues)
error: called from
    pycall_sympy__ at line 191 column 5
    valid_sym_assumptions at line 38 column 10
    assumptions at line 82 column 7
    syms at line 97 column 13
```

Of course i have tried `sympref reset` but still no luck...

**Comment by fugohan** [comment] 2021-06-12 11:04
Same problem with Ubuntu 20.04 for me. 

```
Symbolic pkg v2.9.0: Traceback (most recent call last):
  File "<stdin>", line 28, in <module>
AttributeError: '_PrintFunction' object has no attribute '__globals__'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 12, in octoutput_drv
  File "<stdin>", line 54, in octoutput
  File "<stdin>", line 55, in octoutput
AttributeError: module 'sympy' has no attribute 'compatibility'
Closing the Python communications link.

error: Python exception: AttributeError: '_PrintFunction' object hasno attribute '__globals__'
    occurred in python_header import block.
    Try "sympref reset" and repeat your command?
    (consider filing an issue at https://github.com/cbm755/octsympy/issues)
error: called from
    pycall_sympy__ at line 191 column 5
    valid_sym_assumptions at line 38 column 10
    assumptions at line 82 column 7
    syms at line 97 column 13
```

I fixed it by uninstalling sympy and installing an older version of sympy (1.5.1). 

```
pip3 uninstall sympy 
pip3 install sympy==1.5.1
```

**Comment by j-j-v** [comment] 2021-07-24 10:16
ditto. sympy 1.8, mpmath 1.2.1 (a sympy dependency), symbolic-2.9.0 here. for now rolling back to 1.5.1 for sympy (as shown how above) worked.

**Comment by mtmiller** [comment] 2021-09-02 20:23
This is a duplicate of #1023, closing.

**Closed by mtmiller** 2021-09-02 20:23 UTC
