### ISSUE TITLE
`sympref` test fails when in read-only directory

### ISSUE THREAD

**Issue by mmuetzel** [cbm755/octsympy#1060] opened 2022-02-19 12:15 UTC
When the current directory has read-only access, the following BIST is failing:
https://github.com/cbm755/octsympy/blob/5b58530f4ada78c759829ae703a0e5d9832c32d4/inst/sympref.m#L424-L434

The error message is:
```
>>>>> processing [snip]\share\octave\packages\symbolic-2.9.0\sympref.m
***** test
 sympref('ipc', 'systmpfile');
 syms x
 delete('tmp_python_cmd.py')
!!!!! test failed
fprintf: invalid stream number = -1
shared variables     sympref_orig =

      scalar structure containing the fields:

        ipc = default
        display = ascii
        digits = 32
        quiet = 0

***** error <line 1> pycall_sympy__ ('raise ValueError')
!!!!! error failed.
Expected <line 1>, but got <fprintf: invalid stream number = -1>

***** error <line 1> pycall_sympy__ ('raise ValueError', struct('a', 1, 'b', 'word'))
!!!!! error failed.
Expected <line 1>, but got <fprintf: invalid stream number = -1>
```

That is the case if the symbolic package is installed as a "system" package at a read-only location and a user executes `pkg test symbolic`.

Would it be possible to have the temporary file be written to a location where the user should have write access? E.g., the `TMP` directory?

See also: https://savannah.gnu.org/bugs/index.php?59343

**Comment by cbm755** [comment] 2022-04-09 02:12
I have not yet been able to reproduce this but it makes sense and would be good to fix (so that we could use `pkg test symbolic` instead fo the hacky forked `octsympy_tests` that I have in place right now).

**Comment by cbm755** [comment] 2022-04-09 02:15
More background: `sympref ipc systmpfile` turns this mode on.  What we need here is to change that code (somewhere in `inst/private`) to make the tmp file somewhere other than `pwd`.   See the linked upstream bugs for hints.

**Comment by cbm755** [comment] 2022-06-18 16:26
@alexvong1995 are you able to reproduce this?

(I think I understand the problem but unsure about how to make it happen on my own computer)

**Comment by cbm755** [comment] 2022-06-20 21:50
Here's part of it:
```
> pkg load symbolic
> sympref ipc systmpfile
> cd /home   # or anywhere else without write perm
> syms x
> syms x
error: fprintf: invalid stream number = -1
error: called from
    python_ipc_system at line 111 column 5
    python_ipc_driver at line 73 column 15
    pycall_sympy__ at line 164 column 11
    sym at line 452 column 9
    syms at line 160 column 9
```
I'm sure I can fix that one.  Not sure that is a complete fix for this issue or not.

**Comment by alexvong1995** [comment] 2022-06-21 07:09
I think we can use a [read-only bind mount](https://serverfault.com/questions/136515/read-only-bind-mount) to test for this issue. I am busy at the moment. I will present my GSoC weekly report and start working on this issue later today.

**Comment by alexvong1995** [comment] 2022-06-21 09:48
Right now, Makefile set `tmp` as the default `BUILD_DIR`. I think we should use `${TMPDIR:-/tmp}` to allow building on a read-only source directory.

While `mktemp` is not a POSIX command, `mktemp -d "${TMPDIR:-/tmp}/octsympy-build-dir.XXXXXXXXXX"` should be pretty portable, according to various man pages ([coreutils](https://manpages.debian.org/testing/coreutils/mktemp.1.en.html), [busybox](https://manpages.debian.org/testing/busybox/busybox.1.en.html), [openbsd userland](https://man.openbsd.org/mktemp.1), [freebsd userland](https://www.freebsd.org/cgi/man.cgi?query=mktemp&sektion=1&apropos=0) and [netbsd userland](https://man.netbsd.org/mktemp.1)).

**Comment by mmuetzel** [comment] 2022-06-21 11:29
> Right now, Makefile set `tmp` as the default `BUILD_DIR`. I think we should use `${TMPDIR:-/tmp}` to allow building on a read-only source directory.
> 
> While `mktemp` is not a POSIX command, `mktemp -d "${TMPDIR:-/tmp}/octsympy-build-dir.XXXXXXXXXX"` should be pretty portable, according to various man pages ([coreutils](https://manpages.debian.org/testing/coreutils/mktemp.1.en.html), [busybox](https://manpages.debian.org/testing/busybox/busybox.1.en.html), [openbsd userland](https://man.openbsd.org/mktemp.1), [freebsd userland](https://www.freebsd.org/cgi/man.cgi?query=mktemp&sektion=1&apropos=0) and [netbsd userland](https://man.netbsd.org/mktemp.1)).

Could you please clarify how that relates to the issue here?
This issue is about an error when the current directory is read-only when *executing* commands in Octave.
IIUC, the `Makefile` is only used when *building* the package.

**Comment by alexvong1995** [comment] 2022-06-21 11:45
AFAIK when building octsympy, tests are run with the current directory set to the source directory. If we make the source directory read-only, the `sympref` test should fail during build because of the issue you reported.

My suggestion is that we should make the source directory read-only in CI, in order for this type of bugs to be caught in CI.

Anyway, I agree it is better to open a new issue:  #1141

Thanks for the suggestion!

**Comment by cbm755** [comment] 2022-06-21 19:20
I think this is fixed, at least the particular issue described here.  I might not be surprised if there are other places where the test suite writes files into the CWD.  E.g., `octsympy_tests` itself writes a log file and this causes hassle for our CI.  But we have #1141 and #1142 to try to improve things further.

**Closed by cbm755** 2022-06-21 19:20 UTC
Labels: help wanted, good first issue
