### ISSUE TITLE
CI: pytave python3 run is failing early

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#823] opened 2017-07-27 01:29 UTC
````
Using experimental native Python/C communications with SymPy.

error: SystemError: <class 'tuple'> returned a result with an error set
````

**Comment by cbm755** [comment] 2017-07-27 01:29
e.g., https://travis-ci.org/cbm755/octsympy/jobs/257947749

**Comment by mtmiller** [comment] 2017-07-27 02:34
I can't reproduce, but this looks like a symptom of https://bitbucket.org/mtmiller/pytave/issues/84

**Comment by mtmiller** [comment] 2017-08-04 17:37
I've tried to reproduce this in a clean Docker environment with Ubuntu 14.04 (same as Travis), Octave default branch, Python 3.4 installed with apt, and SymPy 1.1.1 installed with pip, and I don't get this error, test suite runs to completion.

I still suspect this may be fixed once we clear the error state properly, but would be nice to see for sure where this error comes from.

**Comment by mtmiller** [comment] 2017-08-04 17:39
Wait, I see now in the Travis logs that python3 is now Python 3.6.1 rather than the 3.4.3 distributed by Ubuntu. So I'm not exactly reproducing what Travis is doing.

**Comment by mtmiller** [comment] 2017-08-04 17:48
Ok, I think I understand now.

The error does occur when NumPy is not installed, since pytave has a few internal operations that try to test for NumPy types. In Python 3.x (possibly 3.6 and newer), the error state is not being cleared properly.

So now it seems that Travis is installing Python 3.6 outside of apt (under /opt/python/3.6.1). This renders the `apt-get install -y python3-numpy` useless, since it's only installed for /usr/bin/python3 (3.4.3).

So this is a combination of pytave bug and Travis being stupid making our workaround no longer work.

If we change to `pip$PYTHON_VER install --user numpy` that should fix it, and also slow the build down a bit.

**Closed** 2017-08-04 18:57 UTC
