### ISSUE TITLE
How to slim down an equation by using solve?

### ISSUE THREAD

**Issue by DanielMartensson** [cbm755/octsympy#796] opened 2017-05-13 21:50 UTC
Hi!

When I solve a big equation, a got a bit answer back too. I don't want that. I only want in decimal form. To do that, i use vpa(equation, 3) so I can have 3 decimals equation. But that not going solve my problem. 

For exampel. If i have a matrix A and I do the matrix exponential....I can get a huge equation. How do I not get a huge equation? Just decimals? 

I know there is a command named "simplify()", but that's to weak for me. I need something better who can give an approximation instead of exact form.

**Comment by mtmiller** [comment] 2017-05-13 22:08
Please give an example that demonstrates what you think the issue is here. Are you looking to solve a system of equations numerically? If so, why are you using the symbolic package at all? If you are asking for help, please use the Octave help mailing list instead of reporting an issue where there may be none.

**Comment by cbm755** [comment] 2017-06-18 06:20
I guess #809 was your example?  I'll close this as well, but please re-open if you meant this issue to be something different from #809.

**Closed by cbm755** 2017-06-18 06:20 UTC

**Comment by cbm755** [comment] 2017-06-18 06:23
oops I meant #808, sorry for confusion
