### ISSUE TITLE
Problem with fplot

### ISSUE THREAD

**Issue by bydariogamer** [cbm755/octsympy#1032] opened 2020-11-12 10:08 UTC
The fplot function doesn't work:
```
octave:4> f(t)=t^2
f(t) = (symfun)

   2
  t

octave:5> fplot(f,[-2,2])
error: isalnum: not defined for class
error: called from
    fplot at line 108 column 3
octave:6> fplot(f(t),[-2,2])
error: isalnum: not defined for class
error: called from
    fplot at line 108 column 3
```
I think the function does exist and I am using it well.

**Comment by G0rocks** [comment] 2021-02-15 16:35
The function fplot does exist. I'm getting the same error
`error: isalnum: not defined for class
error: called from
    fplot at line 108 column 3
    myProject at line 32 column 1`
This issue: https://github.com/cbm755/octsympy/issues/1031
is related I think

**Comment by G0rocks** [comment] 2021-03-01 08:27
Found a workaround. To use ezplot. ezplot is matlab and octave compatible.

**Comment by latot** [comment] 2021-03-01 15:36
This should be keep open I think..., if is a workaround means the issue is not fixed....

**Comment by G0rocks** [comment] 2021-03-01 15:45
I would agree though I don't know enough about the difference between fplot and ezplot. But it totally worked for me and my group in a group project where some people were using matlab and others octave. I did also find that fplot for octave is on a list of functions that are categorised as "nice to have" though I don't remember where.

If you want to read more about them, here are links.
fplot: https://octave.sourceforge.io/octave/function/fplot.html
ezplot: https://octave.sourceforge.io/octave/function/ezplot.html

**Comment by latot** [comment] 2021-03-01 15:53
Yes, but an issue is to know this things, and who knows or want to try to fix will do it, you are not forced to fix it, but keep it open to know this bug.

**Comment by mtmiller** [comment] 2021-03-02 06:47
Fplot is already listed as a missing function on #215. This issue doesn't really add much information, might as well close it as a duplicate.

**Comment by G0rocks** [comment] 2021-03-02 11:09
Thanks @mtmiller that's exactly the list I was talking about. Maybe not exactly a duplicate since this issue is filed as a bug report but the other issue takes care of it so it's good 👍

**Closed** 2021-03-04 11:13 UTC
Labels: duplicate
