### ISSUE TITLE
Should we normalize the bool outputs?

### ISSUE THREAD

**Issue by latot** [cbm755/octsympy#579] opened 2016-09-25 05:22 UTC
Hi, well checking things i found Sympy don't always return the same type of data in bool cases, for example the contains func returns a normal true/false while isdisjoint returns sym true/false.

So, its necessary normalize this behavior in octsympy?

Thx. Cya.

**Comment by mtmiller** [comment] 2016-10-06 18:53
I think that's a good goal. Are there any examples in master that return a sym true/false value instead of an Octave logical? There is no `isdisjoint` yet.

**Comment by cbm755** [comment] 2016-10-07 06:46
This sounds like a dupe of #57 and/or #308.  Something new here?

One way to get a sym true value is:
````
x == x
A = (sym) True
````

If you wanted to 
````
>> A = [x == x  x == y]
A = (sym) [True  x = y]  (1×2 matrix)
>> A(1)
ans = (sym) True
````
IIRC, SMT doesn't have sym true but it at least used to be possible to get one anyway, doing something like the above.

**Comment by cbm755** [comment] 2019-04-06 21:29
Dupe of earlier issues, closing

**Closed by cbm755** 2019-04-06 21:29 UTC
