### ISSUE TITLE
error: operator =: no conversion for assignment of 'class' to indexed 'matrix'

### ISSUE THREAD

**Issue by JavierGamonal** [cbm755/octsympy#910] opened 2018-09-20 03:01 UTC
hi guys, may you help me?

i just got this problem in this code
![asd](https://user-images.githubusercontent.com/43260034/45793408-5399a900-bc68-11e8-9443-bc0d714d3c84.png)
![asd2](https://user-images.githubusercontent.com/43260034/45793409-5399a900-bc68-11e8-9ff8-12d6fa8576b0.png)

**Comment by cbm755** [comment] 2018-09-20 03:40
Next time, please include a reasonable title and find a minimal non-working example instead of two screenshots.

The minimal example is:
```
A = []
A(1) = sym(2)
```

This is known limitation from upstream Octave.

Workaround:
```
>> A = sym([])
A = (sym) []  (empty 0×0 matrix)
>> A(1) = sym(2)
A = (sym) 2
```

**Comment by cbm755** [comment] 2018-09-20 03:48
Dupe of #191, upstream is https://savannah.gnu.org/bugs/index.php?49267

**Closed by cbm755** 2018-09-20 03:48 UTC
