### ISSUE TITLE
How to make octave find sympy in anaconda?

### ISSUE THREAD

**Issue by EricLucife** [cbm755/octsympy#1030] opened 2020-08-28 08:58 UTC
I use Anaconda to install Sympy, but Octave can not find it. Is there any way to help?

**Comment by cbm755** [comment] 2020-08-28 18:58
What does `sympref diagnose` say?

**Comment by EricLucife** [comment] 2020-09-01 05:27
I find the problem. Anaconda ask users to input not ''python3'' but ''python'' .







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cbm755/octsympy"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月29日(星期六) 凌晨2:58
收件人:&nbsp;"cbm755/octsympy"<octsympy@noreply.github.com&gt;;
抄送:&nbsp;"s"<790462960@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [cbm755/octsympy] How to make octave find sympy in anaconda? (#1030)





 
What does sympref diagnose say?

**Comment by cbm755** [comment] 2020-09-01 05:46
Thanks, that makes this a dupe of #1010 I think.

**Closed by cbm755** 2020-09-01 05:46 UTC

**Comment by EricLucife** [comment] 2020-09-02 08:52
The version of sympy is 1.6.2




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cbm755/octsympy"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月1日(星期二) 中午1:46
收件人:&nbsp;"cbm755/octsympy"<octsympy@noreply.github.com&gt;;
抄送:&nbsp;"s"<790462960@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [cbm755/octsympy] How to make octave find sympy in anaconda? (#1030)





 
Thanks, that makes this a dupe of #1010 I think.
