### ISSUE TITLE
Expressions with more than 255 terms cause communication failures

### ISSUE THREAD

**Issue by cfrangos** [cbm755/octsympy#269] opened 2015-12-06 18:56 UTC
I applied the factor() command to a lengthy expression and there is an
error message - see below. I am using Octave 3.8.1 and symbolic 2.1.0
running on an ubuntu linux 64 bit machine.

This seems to indicate a bug in SymPy and/or in symbolic 2.1.0 ?

C. Frangos.

octave:34> sympref display flat
octave:35> q=(x1_x2 + x2_cos(x3) + sin(x1)_cos(x2) + 12345)^10;
octave:36> qe=expand(q);
octave:37> factor(qe)
  File "<stdin>", line 4
SyntaxError: more than 255 arguments
^C
KeyboardInterrupt
Waiting..........
octave:37> q=(x1_x2 + x2_cos(x3) + sin(x1)_cos(x2) + 12345)^9;
octave:38> qe=expand(q);
octave:39> factor(qe)
Waiting.................................
ans = (sym) (x1_x2 + x2_cos(x3) + sin(x1)_cos(x2) + 12345)_*9
octave:40>

**Comment by cbm755** [comment] 2015-12-10 09:37
Hmmm, I cannot reproduce on current version...  Did I get the code right?  (it was hard to read without backtics)

````
>> syms x1 x2 x3 x4
OctSymPy v2.2.4-dev: this is free software without warranty, see source.
Initializing communication with SymPy using a popen2() pipe.
Some output from the Python subprocess (pid 8679) might appear next.
Python 2.7.10 (default, Sep  8 2015, 17:20:17) 
[GCC 5.1.1 20150618 (Red Hat 5.1.1-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> >>> 
OctSymPy: Communication established.  SymPy v0.7.7.dev.
>> 
>> q=(x1*x2 + x2*cos(x3) + sin(x1)*cos(x2) + 12345)^10;
>> qe=expand(q);
````

What is your SymPy version?  What OS and what IPC mechanism are you using?

**Comment by cfrangos** [comment] 2015-12-10 12:47
I am using SymPy 0.7.4.1-1 on mint linux 17.1 (based on ubuntu 
linux 14.04). What is IPC ?

The Octave commands leading to the error message are given below.

octave:34> sympref display flat
octave:35> q=(x1*x2 + x2*cos(x3) + sin(x1)*cos(x2) + 12345)^10;
octave:36> qe=expand(q);
octave:37> factor(qe)
  File "<stdin>", line 4
SyntaxError: more than 255 arguments
^C
KeyboardInterrupt
Waiting..........
octave:37> q=(x1*x2 + x2*cos(x3) + sin(x1)*cos(x2) + 12345)^9;
octave:38> qe=expand(q);
octave:39> factor(qe)
Waiting.................................
ans = (sym) (x1*x2 + x2*cos(x3) + sin(x1)*cos(x2) + 12345)**9
octave:40>



----- Original Message -----

**Comment by cbm755** [comment] 2015-12-11 06:13
That SymPy is rather old.  Symbolic only supports 0.7.5, and soon to be 0.7.6.

IPC is interprocess communication, how we talk to Python (see `help sympref`).  I asked because of the `SyntaxError: more than 255 arguments` line.

Anyway, I'd suggest upgrading your SymPy which I think will fix the problem (re-open if it does not!)

**Comment by cfrangos** [comment] 2015-12-11 09:02
I forgot to mention that Mike Miller found the same error with the latest SymPy - 
see below.

On Sun, Dec 06, 2015 at 12:06:50 +0200, Constantine Frangos wrote:
> I applied the factor() command to a lengthy expression and there is an
> error message - see below. I am using Octave 3.8.1 and symbolic 2.1.0
> running on an ubuntu linux 64 bit machine.
>
> This seems to indicate a bug in SymPy and/or in symbolic 2.1.0 ?

Confirmed here with the latest versions. If you like you can report
this:

https://github.com/cbm755/octsympy/issues

-- 
mike


----- Original Message -----

**Comment by mtmiller** [comment] 2015-12-11 17:45
Yes I can confirm the following, using Octave 4.0.0 and the master branch:

    octave:3> syms x1 x2 x3
    octave:4> q = (x1*x2 + x2*cos(x3) + sin(x1)*cos(x2) + 12345)^10;
    octave:5> qe = expand(q);
    octave:6> factor(qe);
      File "<stdin>", line 4
    SyntaxError: more than 255 arguments
    ^C

**Comment by cbm755** [comment] 2015-12-12 09:07
Works fine in SymPy so its my fault :(

````
In [16]: x1,x2,x3 = symbols('x1,x2,x3')

In [17]: q = (x1*x2 + x2*cos(x3) + sin(x1)*cos(x2) + 12345)**10

In [18]: qe = q.expand()

In [19]: qe.factor()
Out[19]: (x1*x2 + x2*cos(x3) + sin(x1)*cos(x2) + 12345)**10
````

**Comment by mtmiller** [comment] 2015-12-12 13:55
The error (more than 255 arguments) may indicate that it's something with the calling interface between Octave and Python then?

**Comment by cbm755** [comment] 2015-12-14 18:56
Ok, this is because of we store SymPy expressions using their string representation `srepr()`.  We then basically "paste" that string back into the stdin of Python.   E.g.,

````
In [108]: q = Add(*[Symbol('x%.3d' % i) for i in range(0, 10)])

In [109]: srepr(q)
Out[109]: "Add(Symbol('x000'), Symbol('x001'), Symbol('x002'), Symbol('x003'), Symbol('x004'), Symbol('x005'), Symbol('x006'), Symbol('x007'), Symbol('x008'), Symbol('x009'))"

In [110]: q2 = eval(srepr(q))
````

But now if there are more than 255 arguments to the `Add()`, this fails b/c python functions don't accept more than 255 arguments:

````
In [111]: q = Add(*[Symbol('x%.3d' % i) for i in range(0, 256)])

In [112]: q2 = eval(srepr(q))
  File "<string>", line 1
SyntaxError: more than 255 arguments
````
Probably *some* way around this...  early drafts of Symbolic used pickles instead of `srepr`.

**Comment by cbm755** [comment] 2015-12-14 19:00
I filed upstream [Sympy #10259](https://github.com/sympy/sympy/issues/10259) about this.  Maybe someone has an idea or we can fix it there.

**Comment by latot** [comment] 2016-09-24 23:21
I have an idea how fix this, in the eval section (i don't know where is), we can use a try block, then if it fails for this we can make a tmp file with the expression, then import the file and continue working.

**Comment by latot** [comment] 2016-09-25 00:31
Sadly didn't works, its the same problem, if we have some file with manually written:
```
q = A1 + A2 .... + A256
```
we get the same error...
```  File "<stdin>", line 1
SyntaxError: more than 255 arguments
```
i try too compiling the file but didn't works.....

**Comment by cbm755** [comment] 2016-09-25 05:58
This is ultimately a Python problem as explained above:

> python functions don't accept more than 255 arguments.

**Comment by latot** [comment] 2016-09-27 19:05
mm, sadly need works with more than 255, calc the det of 8x8 have over 255, its very probable i'll patch my pyhton.

**Comment by cbm755** [comment] 2018-06-25 20:47
@latot reports https://github.com/sympy/sympy/issues/10259 this is fixed with Python 3.7.  I will test eventually (when I upgrade to Fedora 29 probably) and then hopefully close this.

**Comment by mtmiller** [comment] 2018-06-25 23:40
I have 3.7.0b3, and it looks fixed to me. With 3.6.5 same error as before, but with 3.7.0b3 it is solved after about 3 or 4 minutes of Python crunching away on my system:

```
>> syms x1 x2 x3
>> q = (x1*x2 + x2*cos(x3) + sin(x1)*cos(x2) + 12345)^10;
>> qe = expand (q);
>> factor (qe)
Waiting..................................
ans = (sym)

                                                10
  (x₁⋅x₂ + x₂⋅cos(x₃) + sin(x₁)⋅cos(x₂) + 12345)  

```

**Comment by cbm755** [comment] 2018-06-26 00:00
Thanks @mtmiller!

**Closed by cbm755** 2018-06-26 00:00 UTC
Labels: bug, longterm, upstream

**Comment by cbm755** [comment] 2018-06-29 06:06
Actually, its now fixed in sympy master (version following upcoming sympy 1.2)

**Comment by cbm755** [comment] 2018-06-29 06:07
https://github.com/sympy/sympy/pull/14841
