### ISSUE TITLE
Sym creation on matrix and functions is causing octave to crash when using PyTave IPC

### ISSUE THREAD

**Issue by genuinelucifer** [cbm755/octsympy#473] opened 2016-06-10 21:00 UTC
I started running tests after implementing the variable copying from octave to python using `pycall`. Octave crashed for many tests. On of the reasons (in `findsymbols`) was that symbols are not getting created. Ex: (each of following test cases causes octave to crash)
* syms f(y)
* syms x y a  
  f(x, y) = a
* sym([1 2])  
.  
Since, octave directly closes, I don't have any idea how to see what went wrong. Suggestions?

**Comment by mtmiller** [comment] 2016-06-10 22:12
Can you reproduce this directly using `pycall` without octsympy? If so please file a pytave issue.

**Comment by mtmiller** [comment] 2016-06-11 15:59
I can't reproduce here.

**Comment by cbm755** [comment] 2016-06-11 16:12
I can:
````
>> sym([1 2])
error: octave_base_value::convert_to_str_internal (): wrong type argument '<unknown type>'
````
I'm on Python 2.7, up-to-date PyTave (I think).

**Comment by cbm755** [comment] 2016-06-11 16:21
Minimal non-working example:
````
>> a = sym(1);
>> python_cmd('return 1', {a})
error: octave_base_value::convert_to_str_internal (): wrong type argument '<unknown type>'
````
Cell-array input is broken.

**Comment by cbm755** [comment] 2016-06-11 16:24
@mtmiller: you cannot reproduce unless you're on the `genuinelucifer/pytave_ex` branch...

I looked at `python_ipc_pytave`: I think you need to recurse down into cell arrays.  That's why this works:
````
>> A = python_cmd('return 1', {42})
````
while this fails:
````
>> A = python_cmd('return 1', {sym(42)})
````

**Comment by cbm755** [comment] 2016-06-11 16:25
@genuinelucifer might be helpful in the future to start your branch when filing bugs (unless of course its master).

**Comment by mtmiller** [comment] 2016-06-11 16:28
Ok, confirm here with pytave_ex branch. Sorry for the noise. Yes, please state branch or commit ID if it's specific and not default.

**Comment by cbm755** [comment] 2016-06-11 16:32
I filed https://bitbucket.org/mtmiller/pytave/issues/16 which might make this sort of thing easier to debug.

**Comment by cbm755** [comment] 2016-06-11 16:33
>  start your branch 

err, *state*

**Comment by cbm755** [comment] 2016-06-11 16:33
Also, "you" in https://github.com/cbm755/octsympy/issues/473#issuecomment-225372841 refers to @genuinelucifer

**Comment by genuinelucifer** [comment] 2016-06-11 16:42
Sorry for not stating the branch.
.
I tried a lot of things but still couldn't get it to work.
I guess either we can use 'pyexec' to do most of the variable saving stuff.
Or for the second choice I'm still trying to debug this somehow when using
pycall.
.
I already wrote a recursive function to store the variables. (I'll push it
late). Still facing many issues.
.
One question :
`python_cmd('return _ins',  [1 2])`
What is this code expected to return?
A cell array with the first element as a list [1 2]
Or a list `ans = [1 2]`
Or 2 return values [1, 2] so ans will be 1 but `[a, b] = python_cmd('return
_ins',  [1 2])` would work?

**Comment by cbm755** [comment] 2016-06-11 17:11
> One question :

Run with `ipc popen2` and check...  But I don't think passing double arrays in is supported (yet).

This should work:
````
>> A = python_cmd('return _ins', {1 2})   # note braces not []
A = 
{
  [1,1] =  1
  [1,2] =  2
}
>> 
````

**Comment by cbm755** [comment] 2016-06-11 17:18
Let me explain: in this example, `_ins` will be `[[1, 2]]`: a list of a list.  When `return` returns a list, that list becomes the `vargout` cell-array: so in this case a cell array containing the cell-array `{1, 2}`.  This is documented in help `python_cmd`.

The slightly confusing case is if you return a scalar *not wrapped in a list*.  You might expect this to fail.  Surprisingly it works and become the single output: this was a recent addition from @latot: its convenient when writing `cmd` blocks but potentially confusing when working on `python_cmd` and `python_ipc_*`.

**Comment by cbm755** [comment] 2016-06-11 17:23
Also, feel free to push your recursive version and I'll take a look.  Does it fix `sym([1 2])`?  We'll squash the bugs one at a time ;-)   This `sym([1 2])` bug is most significant I think.

**Comment by genuinelucifer** [comment] 2016-06-11 17:24
Hmm sure. I'll push the changes within the next hour.

**Comment by cbm755** [comment] 2016-06-12 17:15
closing, reopen if I missed something

**Closed by cbm755** 2016-06-12 17:15 UTC
Labels: bug
